import cv2
import numpy as np
import pytest

from app.scale_estimation import (
    ESTABLISHED,
    NOT_VERIFIED,
    convert_font_height_to_mm,
    estimate_barcode_scale,
)
from app.db.models import VerificationState
from app.rule_engine import evaluate_font_size_condition


def _barcode_image() -> np.ndarray:
    """A synthetic high-contrast, 95-module-wide linear barcode image."""
    image = np.full((180, 500, 3), 255, dtype=np.uint8)
    for module in range(95):
        if module % 3 != 1:
            image[30:150, 60 + module * 4 : 60 + (module + 1) * 4] = 0
    return image


def test_ean13_barcode_establishes_auditable_nominal_scale():
    image = _barcode_image()
    result = estimate_barcode_scale(
        image,
        {"x": 60, "y": 30, "width": 380, "height": 120},
        "EAN13",
    )

    assert result["status"] == ESTABLISHED
    assert result["pixels_per_mm"] == round(380 / 31.35, 6)
    assert result["reference"]["encoded_modules"] == 95
    assert result["reference"]["nominal_x_dimension_mm"] == 0.330
    assert "pixels_per_mm" in result["derivation"]

    font = convert_font_height_to_mm(24, result)
    assert font["status"] == ESTABLISHED
    assert 1.9 < font["font_height_mm"] < 2.1
    assert "font_height_mm" in font["derivation"]


def test_missing_or_unusable_barcode_never_invents_a_scale():
    image = np.full((180, 500, 3), 255, dtype=np.uint8)
    result = estimate_barcode_scale(image, None, None)

    assert result["status"] == NOT_VERIFIED
    assert result["pixels_per_mm"] is None
    assert result["millimetre_values_available"] is False

    font = convert_font_height_to_mm(24, result)
    assert font["status"] == NOT_VERIFIED
    assert font["pixels_per_mm"] is None


def test_font_rule_is_not_verified_without_a_provenance_bearing_scale():
    verdict, reason = evaluate_font_size_condition(
        {"font_height_px": 24},
        {"status": NOT_VERIFIED, "pixels_per_mm": None},
        {"min_font_size_mm": 1.0},
    )

    assert verdict == VerificationState.NOT_VERIFIED
    assert "not verified" in reason.lower()


def _generate_ean13_image(dpi: int, module_width_mm: float = 0.330):
    """Generate a real checksum-valid EAN-13 barcode image at a known DPI.

    Returns (image_path, ground_truth_pixels_per_mm) — the ground-truth ratio
    comes solely from the known DPI, completely independent of
    scale_estimation.py.
    """
    import os
    import tempfile

    import barcode
    from barcode.writer import ImageWriter

    tmp_dir = tempfile.mkdtemp()
    # Use a valid EAN-13 with correct checksum
    ean = barcode.get("ean13", "5901234123457", writer=ImageWriter())
    opts = {
        "module_width": module_width_mm,
        "module_height": 25,
        "quiet_zone": 6.5,
        "font_size": 0,
        "text_distance": 0,
        "write_text": False,
        "dpi": dpi,
    }
    saved_path = ean.save(os.path.join(tmp_dir, "barcode"), options=opts)
    ground_truth_ppmm = dpi / 25.4
    return saved_path, ground_truth_ppmm, tmp_dir


def _decode_ean13(image_path: str) -> dict:
    """Decode a real image through app.barcode.BarcodeDecoder.

    Returns the first EAN-13 result dict, or raises AssertionError if decode
    fails — this test must NEVER silently skip a failed decode.
    """
    import sys
    from unittest.mock import MagicMock

    # conftest.py mocks pyzbar on Windows; detect that
    if isinstance(sys.modules.get("pyzbar"), MagicMock):
        return None
    if isinstance(sys.modules.get("pyzbar.pyzbar"), MagicMock):
        return None

    from app.barcode import BarcodeDecoder

    decoder = BarcodeDecoder()
    results = decoder.decode(image_path)
    return next((r for r in results if r["format"] in ("EAN13", "EAN-13")), None)


@pytest.mark.parametrize(
    "dpi, module_width_mm",
    [(300, 0.330), (600, 0.500)],
    ids=["300dpi-0.33mm", "600dpi-0.50mm"],
)
def test_pyzbar_bbox_matches_bar_pattern_not_full_symbol(dpi, module_width_mm):
    """Verify pyzbar bbox corresponds to the 95-module bar pattern (31.35mm
    at 0.330mm X-dim), NOT the 113-module full symbol including quiet zones
    (37.29mm).

    Uses a real, checksum-valid EAN-13 generated by python-barcode at a known
    DPI.  Ground-truth pixels-per-mm is computed from the DPI alone
    (dpi / 25.4), completely independent of scale_estimation.py.  The decoded
    bbox width is converted to mm using that ground-truth ratio and compared
    to 95*0.330 = 31.350mm (bar pattern) vs 113*0.330 = 37.290mm (full
    symbol).

    Runs at two DPIs/module widths for a stronger regression signal.

    If this test fails, _MODULES_WIDE and _NOMINAL_SYMBOL_WIDTH_MM in
    scale_estimation.py must be updated to 113 / 37.29 mm.
    """
    saved_path, ground_truth_ppmm, tmp_dir = _generate_ean13_image(dpi, module_width_mm)
    try:
        result = _decode_ean13(saved_path)
        if result is None:
            pytest.skip("pyzbar is mocked (Windows) — this test requires real libzbar")

        bbox = result["bbox"]
        bbox_width_px = bbox["width"]

        # Convert bbox width to mm using ground-truth DPI ratio
        bbox_width_mm = bbox_width_px / ground_truth_ppmm

        # Predicted widths
        bar_pattern_mm = 95 * 0.330  # 31.350 mm
        full_symbol_mm = 113 * 0.330  # 37.290 mm

        # Assert decode succeeded (non-empty, positive dimensions)
        assert bbox_width_px > 0, f"decoded bbox has non-positive width: {bbox_width_px}"

        # Assert bbox width in mm is within 2% of the 95-module prediction
        tolerance = 0.02  # 2%
        deviation_95 = abs(bbox_width_mm - bar_pattern_mm) / bar_pattern_mm
        deviation_113 = abs(bbox_width_mm - full_symbol_mm) / full_symbol_mm

        assert deviation_95 < tolerance, (
            f"pyzbar bbox width {bbox_width_px:.1f}px = {bbox_width_mm:.3f}mm "
            f"(ground-truth ppmm={ground_truth_ppmm:.4f} from {dpi} DPI). "
            f"Deviation from 95-module prediction ({bar_pattern_mm:.3f}mm): "
            f"{deviation_95:.1%} exceeds {tolerance:.0%} tolerance. "
            f"_MODULES_WIDE and _NOMINAL_SYMBOL_WIDTH_MM may need updating to "
            f"113 / 37.29mm."
        )

        # Also assert it's NOT close to 113-module (catch the opposite error)
        assert deviation_113 > 0.05, (
            f"pyzbar bbox width {bbox_width_px:.1f}px = {bbox_width_mm:.3f}mm "
            f"is suspiciously close to the 113-module prediction "
            f"({full_symbol_mm:.3f}mm, deviation {deviation_113:.1%}). "
            f"This suggests pyzbar bbox includes quiet zones — "
            f"re-examine the 95-module assumption."
        )
    finally:
        import shutil
        shutil.rmtree(tmp_dir, ignore_errors=True)
