"""add inspection_locations table

Revision ID: 990b42ec209b
Revises: d189e3b61213
Create Date: 2026-09-05 08:23:22.498645
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '990b42ec209b'
down_revision: Union[str, None] = 'd189e3b61213'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
