"""initial tables

Revision ID: cd318337fc4e
Revises: 
Create Date: 2026-09-03 11:24:17.789177
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'cd318337fc4e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('officers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'INSPECTOR', 'VIEWER', name='officer_role'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_officers_email'), 'officers', ['email'], unique=True)
    op.create_table('products',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('identity', sa.String(), nullable=True),
    sa.Column('brand', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('manufacturer', sa.String(), nullable=True),
    sa.Column('packer', sa.String(), nullable=True),
    sa.Column('importer', sa.String(), nullable=True),
    sa.Column('country_of_origin', sa.String(), nullable=True),
    sa.Column('quantity_value', sa.Float(), nullable=True),
    sa.Column('quantity_unit', sa.String(), nullable=True),
    sa.Column('mrp_amount', sa.Float(), nullable=True),
    sa.Column('mrp_currency', sa.String(), nullable=True),
    sa.Column('date_manufacture', sa.Date(), nullable=True),
    sa.Column('date_best_before', sa.Date(), nullable=True),
    sa.Column('date_use_by', sa.Date(), nullable=True),
    sa.Column('consumer_care', sa.Text(), nullable=True),
    sa.Column('unit_sale_price_amount', sa.Float(), nullable=True),
    sa.Column('unit_sale_price_currency', sa.String(), nullable=True),
    sa.Column('barcode_code', sa.String(), nullable=True),
    sa.Column('barcode_format', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_barcode_code'), 'products', ['barcode_code'], unique=False)
    op.create_index(op.f('ix_products_brand'), 'products', ['brand'], unique=False)
    op.create_index(op.f('ix_products_category'), 'products', ['category'], unique=False)
    op.create_table('rule_sets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('rule_version', sa.String(), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('jurisdiction', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('officer_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('target_type', sa.String(), nullable=False),
    sa.Column('target_id', sa.UUID(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['officer_id'], ['officers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_officer_id'), 'audit_log', ['officer_id'], unique=False)
    op.create_table('rules',
    sa.Column('rule_id', sa.String(), nullable=False),
    sa.Column('rule_set_id', sa.UUID(), nullable=False),
    sa.Column('source_document', sa.String(), nullable=False),
    sa.Column('clause', sa.String(), nullable=False),
    sa.Column('applicability', sa.Text(), nullable=False),
    sa.Column('required_declaration', sa.String(), nullable=False),
    sa.Column('validation_conditions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('measurement_requirements', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('exceptions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('evidence_requirements', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['rule_set_id'], ['rule_sets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('rule_id')
    )
    op.create_index(op.f('ix_rules_rule_set_id'), 'rules', ['rule_set_id'], unique=False)
    op.create_table('scans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='scan_status'), nullable=False),
    sa.Column('overall_status', sa.Enum('SATISFIED', 'VIOLATION', 'NOT_VERIFIED', 'CONFLICT', 'NOT_APPLICABLE', name='verification_state'), nullable=True),
    sa.Column('warnings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('image_quality', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scans_product_id'), 'scans', ['product_id'], unique=False)
    op.create_index(op.f('ix_scans_status'), 'scans', ['status'], unique=False)
    op.create_table('declarations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('scan_id', sa.UUID(), nullable=False),
    sa.Column('field_name', sa.String(), nullable=False),
    sa.Column('extracted_value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('rule_id', sa.String(), nullable=True),
    sa.Column('verdict', sa.Enum('SATISFIED', 'VIOLATION', 'NOT_VERIFIED', 'CONFLICT', 'NOT_APPLICABLE', name='verification_state'), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('officer_correction', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_declarations_field_name'), 'declarations', ['field_name'], unique=False)
    op.create_index(op.f('ix_declarations_rule_id'), 'declarations', ['rule_id'], unique=False)
    op.create_index(op.f('ix_declarations_scan_id'), 'declarations', ['scan_id'], unique=False)
    op.create_index(op.f('ix_declarations_verdict'), 'declarations', ['verdict'], unique=False)
    op.create_table('images',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('scan_id', sa.UUID(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_images_scan_id'), 'images', ['scan_id'], unique=False)
    op.create_table('inspections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('scan_id', sa.UUID(), nullable=False),
    sa.Column('officer_id', sa.UUID(), nullable=False),
    sa.Column('actions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['officer_id'], ['officers.id'], ),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inspections_officer_id'), 'inspections', ['officer_id'], unique=False)
    op.create_index(op.f('ix_inspections_scan_id'), 'inspections', ['scan_id'], unique=False)
    op.create_table('report_exports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('scan_id', sa.UUID(), nullable=False),
    sa.Column('format', sa.String(), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_exports_scan_id'), 'report_exports', ['scan_id'], unique=False)
    op.create_table('compliance_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('declaration_id', sa.UUID(), nullable=False),
    sa.Column('rule_id', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('SATISFIED', 'VIOLATION', 'NOT_VERIFIED', 'CONFLICT', 'NOT_APPLICABLE', name='verification_state'), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['declaration_id'], ['declarations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rule_id'], ['rules.rule_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compliance_results_declaration_id'), 'compliance_results', ['declaration_id'], unique=False)
    op.create_index(op.f('ix_compliance_results_rule_id'), 'compliance_results', ['rule_id'], unique=False)
    op.create_table('evidence',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_type', sa.Enum('OCR', 'BARCODE', 'QR', 'PRODUCT_DATABASE', 'MANUAL_ENTRY', 'OFFICER_CORRECTION', 'PRIOR_RECORD', name='evidence_source_type'), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('image_id', sa.UUID(), nullable=True),
    sa.Column('bbox', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('preprocessing_variant', sa.String(), nullable=True),
    sa.Column('extracted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('declaration_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['declaration_id'], ['declarations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_declaration_id'), 'evidence', ['declaration_id'], unique=False)
    op.create_index(op.f('ix_evidence_image_id'), 'evidence', ['image_id'], unique=False)
    op.create_index(op.f('ix_evidence_source_type'), 'evidence', ['source_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_evidence_source_type'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_image_id'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_declaration_id'), table_name='evidence')
    op.drop_table('evidence')
    op.drop_index(op.f('ix_compliance_results_rule_id'), table_name='compliance_results')
    op.drop_index(op.f('ix_compliance_results_declaration_id'), table_name='compliance_results')
    op.drop_table('compliance_results')
    op.drop_index(op.f('ix_report_exports_scan_id'), table_name='report_exports')
    op.drop_table('report_exports')
    op.drop_index(op.f('ix_inspections_scan_id'), table_name='inspections')
    op.drop_index(op.f('ix_inspections_officer_id'), table_name='inspections')
    op.drop_table('inspections')
    op.drop_index(op.f('ix_images_scan_id'), table_name='images')
    op.drop_table('images')
    op.drop_index(op.f('ix_declarations_verdict'), table_name='declarations')
    op.drop_index(op.f('ix_declarations_scan_id'), table_name='declarations')
    op.drop_index(op.f('ix_declarations_rule_id'), table_name='declarations')
    op.drop_index(op.f('ix_declarations_field_name'), table_name='declarations')
    op.drop_table('declarations')
    op.drop_index(op.f('ix_scans_status'), table_name='scans')
    op.drop_index(op.f('ix_scans_product_id'), table_name='scans')
    op.drop_table('scans')
    op.drop_index(op.f('ix_rules_rule_set_id'), table_name='rules')
    op.drop_table('rules')
    op.drop_index(op.f('ix_audit_log_officer_id'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_table('rule_sets')
    op.drop_index(op.f('ix_products_category'), table_name='products')
    op.drop_index(op.f('ix_products_brand'), table_name='products')
    op.drop_index(op.f('ix_products_barcode_code'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_officers_email'), table_name='officers')
    op.drop_table('officers')
    # ### end Alembic commands ###
