"""add password_hash to officers

Revision ID: d189e3b61213
Revises: cd318337fc4e
Create Date: 2026-09-03 11:30:54.595115
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'd189e3b61213'
down_revision: Union[str, None] = 'cd318337fc4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Add column nullable first so existing rows don't break
    op.add_column('officers', sa.Column('password_hash', sa.String(), nullable=True))
    # Backfill existing officers with a placeholder (they must reset via create_officer.py)
    op.execute("UPDATE officers SET password_hash = 'CHANGE_ME' WHERE password_hash IS NULL")
    op.alter_column('officers', 'password_hash', nullable=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('officers', 'password_hash')
    # ### end Alembic commands ###
